In [13]:
import numpy as np
k=np.random.randint(0,10,size=(3,3))
rows,cols=k.shape
print(k)

[[3 4 6]
 [9 4 4]
 [5 5 4]]


In [14]:
kk=k.reshape((1,rows,cols))
print(kk.shape)
print(kk)

(1, 3, 3)
[[[3 4 6]
  [9 4 4]
  [5 5 4]]]


In [15]:
kkk=np.tile(kk,(3,1,1,1))
print(kkk.shape)
print(kkk)

(3, 1, 3, 3)
[[[[3 4 6]
   [9 4 4]
   [5 5 4]]]


 [[[3 4 6]
   [9 4 4]
   [5 5 4]]]


 [[[3 4 6]
   [9 4 4]
   [5 5 4]]]]


In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [19]:
print(type(kkk))
kernel=torch.tensor(kkk)
print(type(kernel))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [22]:
a=torch.Tensor([7,6,3])
print(a)
print(a[0])

tensor([7., 6., 3.])
tensor(7.)
